

site_name: ICD 11 Code Tools


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: index.md

- Setting Up Tools:
  - Setting up Python: setup/anaconda.md
  - Setting up Environment: setup/env.md
  - Setting up Elasticsearch : setup/elastic.md
  - Setting up Neo4J: setup/neo4j.md
  - Setting up MongoDB: setup/mongo.md
  - Setting up Git: setup/git.md

- Introduction: 
  - Workflow: workflow.md
  
- Download and Processing:
  - Download Pipeline: download/download.md
  - Parsing Pipeline: parsing/parsing.md
  
- Database and Functionality:
  - NoSQL Database: mongo/mongo.md
  - Indexing Database: indexing/indexing.md
  - Graph Database: graph/graph.md
  
- Algorithm and Querries:
  - Queries in NetworkX: graph/query_nx.md
  - Queries in Neo4j: graph/query_neo4j.md

- User Interface: 
  - Flask: flask/flask.md
  
- Data Analysis: 
  - Exploratory: explore/explore.md 
  - Model Based Analysis:
      - Clustering: models/clustering.md
      - Link Prediction : models/link.md
      - Randomwalk : models/random-walk.md



 
 
